# Generated by Django 5.1.1 on 2024-09-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("in_active", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
    ]
